# Generated by Django 4.2.3 on 2023-07-19 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_featured',
        ),
    ]
